### ISSUE TITLE
"KKK VOCE MANO TROLLED ZAP ZAP"

### ISSUE THREAD

**Issue by Chaprnks** [RealAtom/hyaxe#4]
Todos os arquivos do módulo contêm este:

"KKK VOCE MANO TROLLED ZAP ZAP"....

**Comment by RealAtom** [comment]
Fixed, is a encoding error.

**Comment by Chaprnks** [comment]
Majority of the files still have the "KKK VOCE MANO TROLLED ZAP ZAP" spammed in them.

![oX8W](https://user-images.githubusercontent.com/6340970/152664285-91dfbc37-d989-4ca5-870e-3550897ff9b5.png)
![oX8J](https://user-images.githubusercontent.com/6340970/152664292-5d844a95-8b11-4f60-9964-2cadee1feeb7.png)
![oX8y](https://user-images.githubusercontent.com/6340970/152664294-a8152a9f-497c-47e4-abc2-6a64d2027f25.png)
